ProyectoWebJec/urls.py
from django.contrib import admin
from django.urls import path, include
from ProyectoWebJecApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('sendmail/', include('sendmail.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
    
    path('', include('ProyectoWebJecApp.urls')),
]

blog/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.blog, name="Blog"),
    path('categorias/<int:categoria_id>/', views.categorias, name="categoriaa"),

#Dentro del "name" que contiene como valor "categoriaa", esta haciendo referencia
#a la clave con la cual vamos a llamar al path desde la hoja de html en la sección de filtrado de 
#categorias de entradas de blog.
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns = [
    
    path('agregar/<int:producto_id>', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>', views.restar_producto, name="restar"),
    path('limpiar/<int:producto_id>', views.limpiar_carro, name="limpiar"),   

]

#Para llamar desde el template vamos a utilizar las clave valor que agregamos aquí: EJEMPLO: <a href="{% 'carro:agregar' producto.id %}...

tienda/urls.py
from django.urls import path

from . import views


urlpatterns = [
    
    path('tienda', views.tienda, name="Tienda"),
    path('categorias/<int:categoria_id>/', views.categorias, name="categoria2"),




]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from email.policy import default
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50) 
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='categoriaProd'
        verbose_name_plural='categoriasProd'

    def __str__(self):
        return self.nombre


class Productos(models.Model):
    nombre=models.CharField(max_length=50,null=True) 
    precio=models.IntegerField(null=True)
    stock=models.IntegerField(null=True)
    imagen=models.ImageField(upload_to='tienda', null=True, blank=True)
    #Vamos a crear una propiedad "autor" para que cada entrada de blog que realice un autor determinado, al momento de retirarse la página, todos sus blogs sean borradas.
    #autor=models.ForeignKey(User, on_delete=models.CASCADE)
    #Ahora vamos a crear esta propiedad que nos indica que un blog puede pertenecer a varias categorias.
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render

from .carro import Carro
from tienda.models import Productos
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Productos.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Productos.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Productos.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Tienda")


def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render

from .models import Productos, CategoriaProd

# Create your views here.

def tienda(request):

    produ=Productos.objects.all()
    return render(request, './Tienda.html', {"produs": produ})

#El ultimo parámetro del render() "{"posteos": posts}" es una forma de llamar a la base de datos.
#Es una Queryset. Al parecer un Queryset es una especie de diccionario con una colección de tods los objetos
#de la base de datos. Y se la llama con un nombre de variable, en este caso "posteos" dos puntos y el nombre 
#de la variable que creamos arriba que contiene todos los objetos osea "post" (posts=Post.objects.all())

def categorias(request, categoria_id):

    categoria2=CategoriaProd.objects.get(id=categoria_id)
    produ=Productos.objects.filter(categorias=categoria2)
    return render(request, "tienda/categoria.html",{'categoria2':categoria2,"produs": produ})

tienda/templates/carro/widget.html
<table class="table table-bordered" style="background-color: rgba(255, 255, 255, 0.89); color: black;">

    <thead>
        <tr>

            <th colspan="3" class="text-center">

                Carro compras

            </th>

        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>


        </tr>


    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        {{value.precio}} $&nbsp;&nbsp;<a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>&nbsp;

                        
                    </td>

                </tr>

            {% endfor %}

        {% else %}
            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        Sin productos
                    </div>

                </td>

            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro}} $ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {% if request.session.carro.items %}
                <a href="{% url 'procesar_pedidos' %}" class="btn btn-success">Comprar</a>
                {% endif %}


            </td>


        </tr>

    </tfoot>


</table>